name: domain
description: The layer containing all business objects and core business rules.

version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  codenic_bloc_use_case: ^0.1.0-dev.8
  collection: ^1.15.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0

flutter:
  module:
    androidX: true
    androidPackage: com.orga.domain
    iosBundleIdentifier: com.orga.domain
