name: application
description: The layer responsible for managing the data flow between the Presentation and Domain layer.

version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  domain:
    path: ../domain
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^2.4.0

flutter:
  module:
    androidX: true
    androidPackage: com.orga.application
    iosBundleIdentifier: com.orga.application
