name: dash_slide_puzzle
description: The root module.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  application: 
    path: modules/application
  domain:
    path: modules/domain
  flutter:
    sdk: flutter

  infrastructure:
    path: modules/infrastructure
  presentation:
    path: modules/presentation


dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true