name: dash_slide_puzzle
description: The root module.

publish_to: "none"

version: 1.1.0+9

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  application:
    path: modules/application
  domain:
    path: modules/domain
  flutter:
    sdk: flutter
  infrastructure:
    path: modules/infrastructure
  presentation:
    path: modules/presentation

dev_dependencies:
  flutter_launcher_icons: ^0.9.2

  flutter_test:
    sdk: flutter

  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path_android: "assets/icons/app_icon_square_rounded.png"
  image_path_ios: "assets/icons/app_icon_square_sharp.png"
  adaptive_icon_background: "assets/icons/app_icon_background.png"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
