name: presentation
description: The layer managing all the UI widgets and user interaction.

version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  application:
    path: ../application
  draggable_fab: ^0.1.4
  flutter:
    sdk: flutter
  flutter_animated_dialog: ^2.0.1
  flutter_bloc:
    ^8.0.1  
  flutter_localizations:
    sdk: flutter
  flutter_social_button: ^1.1.4
  font_awesome_flutter: ^9.2.0  
  get_it: ^7.2.0
  google_fonts: ^2.3.1
  image: ^3.1.3
  intl: ^0.17.0
  liquid_progress_indicator: ^0.4.0
  loading_animations: ^2.2.0
  rive: ^0.8.1
  simple_shadow: ^0.3.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0


flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/audio/sfx/
    - assets/images/day_cycles/
    - assets/images/dash_sprites/body/
    - assets/images/dash_sprites/comb/
    - assets/images/dash_sprites/devices/
    - assets/images/dash_sprites/faces/
    - assets/images/dash_sprites/tail/
    - assets/images/dash_sprites/wand/
    - assets/images/dash_sprites/wings/
    - assets/images/logos/
    - assets/images/spells/
    - assets/images/throwables/

  fonts:
    - family: Bangers
      fonts:
        - asset: fonts/Bangers-Regular.ttf


  module:
    androidX: true
    androidPackage: com.orga.presentation
    iosBundleIdentifier: com.orga.presentation
