name: presentation
description: The layer managing all the UI widgets and user interaction.

version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  application:
    path: ../application
  draggable_fab: ^0.1.4
  flutter:
    sdk: flutter
  flutter_animated_dialog: ^2.0.1

  flutter_bloc:
    ^8.0.1  
  flutter_social_button: ^1.1.3

  font_awesome_flutter: ^9.2.0  
  get_it: ^7.2.0
  google_fonts: ^2.3.1
  image: ^3.1.1
  liquid_progress_indicator: ^0.4.0
  loading_animations: ^2.2.0
  simple_shadow: ^0.3.0
  url_launcher: ^6.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0


flutter:
  uses-material-design: true

  assets:
    - assets/audio/sfx/
    - assets/images/background/
    - assets/images/dashatars/
    - assets/images/dashatars/blue/
    - assets/images/dashatars/blue/001/
    - assets/images/dashatars/blue/001/tiles/
    - assets/images/dashatars/blue/002/
    - assets/images/dashatars/blue/002/tiles/
    - assets/images/dashatars/indigo/001/
    - assets/images/dashatars/indigo/001/tiles/
    - assets/images/dashatars/indigo/002/
    - assets/images/dashatars/indigo/002/tiles/
    - assets/images/dashatars/yellow/001/
    - assets/images/dashatars/yellow/001/tiles/
    - assets/images/dashatars/yellow/002/
    - assets/images/dashatars/yellow/002/tiles/
    - assets/images/day_cycles/
    - assets/images/dash_sprites/body/
    - assets/images/dash_sprites/comb/
    - assets/images/dash_sprites/devices/
    - assets/images/dash_sprites/faces/
    - assets/images/dash_sprites/tail/
    - assets/images/dash_sprites/wand/
    - assets/images/dash_sprites/wings/
    - assets/images/logos/
    - assets/images/spells/
    - assets/images/throwables/

  module:
    androidX: true
    androidPackage: com.orga.presentation
    iosBundleIdentifier: com.orga.presentation
